apiVersion: v1
kind: Pod
metadata:
 name: secret-injecting-configmap
spec:
 containers:
  - image: venkateshbabu042/underwater:latest
    name: firstcontainer
    imagePullPolicy: Never
    volumeMounts:
    - name: test
      mountPath: "/secret-values"
 volumes: 
   - name: test
     secret:
      secretName: app-secrets