apiVersion: v1
kind: Pod
metadata:
 name: day10
 labels:
  env: testing
  department: DevOps
spec:
  containers:
   - name: container1
     image: nginx
   - name: container2
     image: ubuntu
     command: ["/bin/bash", "-c", "while true; do echo This is Day07 of 30DaysOfKubernetes;sleep 5 ; done"]
     ports:
      - containerPort: 80