apiVersion: v1
kind: Service
metadata:
    name: svc-lb
spec:
    type: LoadBalancer
    selector:
        tag: DevOps
    ports:
    - name: port-lb
      protocol: TCP
      port: 80
      targetPort: 80