apiVersion: v1
kind: Pod
metadata:
  name: day10-pod2
  labels:
    env: testing
    department: DevOps
spec:
  containers:
    - name: container2
      image: httpd
      ports:
      - containerPort: 80