apiVersion: v1
kind: Service
metadata:
  name: underwater-service
spec:
  selector:
    app.kubernetes.io/name: underwater-web-app
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
  type: LoadBalancer